spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate.ddl-auto: create-drop
  data:
    jpa.repositories.bootstrap-mode: default
  sql:
    init.mode: always # always/never
  h2:
    console.enabled: true
        